export const EMPLOYEE_NAMES = [
  "Ahmed Azmeen",
  "Ahmed Ruzaan",
  "Ibrahim Nuhan",
  "Aminath Samaha",
  "Aishath Samaha",
  "Imraan Shareef",
  "Aminath Shazuly",
  "Fazeel Ahmed",
  "Hussain Sazeen",
  "Mohamed Suhail",
  "Aminath Shaliya",
  "Fathimath Jazlee",
  "Aminath Nuha",
  "Hussain Nausam",
  "Fathimath Zeyba",
  "Fathimath Usaira",
  "Mohamed Waheedh",
  "Aishath Shaila",
  "Azlifa Saleem",
  "Aishath Shabaana",
];
