import { QueryProvider } from "@/Providers/QueryProvider";
import { UserProvider } from "@/Providers/UserProvider";
import { QueryWarmup } from "@/components/query/QueryWarmup";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import "./globals.css";

import { Plus_Jakarta_Sans } from "next/font/google";

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-plus-jakarta",
});

export const metadata: Metadata = {
  title: "Innamaadhoo Council",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={plusJakarta.className}>
        <ClerkProvider>
          <QueryProvider>
            <QueryWarmup />
            <UserProvider>
              <main>{children}</main>
            </UserProvider>
          </QueryProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
